version: '2'
services:

  frontend:
    container_name: 'db-ass-mongo-frontend'
    hostname: db-ass-mongo-frontend
    restart: always
    build: 
      context: ./tweet-frontend
      dockerfile: Dockerfile
    ports:
      -80:80
      -443:443

  api:
    container_name: 'db-ass-mongo-backend'
    hostname: db-ass-mongo-backend
    build: 
      context: ./tweet-backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - TWITTER=${TWITTER}

  